profiles: dev

server:
  port: 8080

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/test3?useSSL=false&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://localhost:3306/test3
    username: root
    password: 1234
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    initialSize: 2
    maxActive: 300
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 200

  # jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# mybatis配置
mybatis:
  mapper-locations: classpath*:/mapping/*Mapper.xml
  type-aliases-package: com.dormitory.vo

# 日志配置 输出debug级日志
logging:
  level:
    com.quick.mapper: DEBUG

